"""Phase 14 Tier-2 driver — generate the canonical headline result from the
FROZEN ``best_checkpoint.pt`` (epoch 1969), NOT a fresh retrain.

This is the load-bearing headline number for the AIChE revision. It is
generated by loading the epoch-1969 ``params_pqc`` (55,) ground-truth tensor
into the locked NON-default ``iqp_sel_55`` circuit (Plan 01, D-14-01/04/07),
generating samples with the checkpoint's STORED scalar ``mu``/``sigma`` and a
FIXED generation seed, and evaluating via ``revision.core.eval`` ONLY (D-10-20)
on the pinned native Pipeline-B (D-14-06) at BOTH scales (OD + log_return).

D-14-03/05 reproduction landmines (mitigated here):
  * The headline comes from the FROZEN checkpoint — never a fresh retrain.
  * mu/sigma are read VERBATIM from the checkpoint / lock JSON — NEVER
    recomputed (a freshly-computed stat would not reproduce the 16 canonical
    figures).
  * The generation seed is FIXED and recorded in the output.

D-14-10 (headline vs reproduction conflation): the output carries an explicit
``source: "frozen_checkpoint_epoch_1969"`` marker so it is NEVER conflated with
the matched-2000ep reproduction instance (which carries
``source: "matched2000_reproduction"``).

T-14-14 (checkpoint identity reuse): ``best_checkpoint.pt``'s sha256 is
re-verified against Plan 01's ``canonical_config_lock.json``
``checkpoint_sha256`` with an explicit ``raise AssertionError`` (survives
``python -O`` — run_multiseed_rollup.py:86-92 idiom) BEFORE any generation.

T-14-04 (device/dtype manifest honesty): a ``device``/``dtype`` manifest is
emitted and the actual backend is hard-asserted. PennyLane's ``default.qubit``
statevector path is CPU-only (D-14-11); the quantum row is CORRECTLY CPU. A
silent CPU/dtype surprise fails loudly.

Repo-root + worktree-aware gitignored-checkpoint resolver copied verbatim from
``run_recover_canonical.py`` (best_checkpoint.pt + qgan_env are .gitignored, so
in a Claude Code worktree they live in the *main* checkout, not the worktree).

revision/core/ is NEVER modified by this driver (T-14-02): it constructs the
already-added NON-default ``iqp_sel_55`` config variant; no core edits.

Usage
-----
    ./qgan_env/bin/python revision/run_canonical_headline.py \\
        [--csv-path ./data.csv] [--generation-seed 42] \\
        [--out revision/results/headline_canonical.json]

Writes ``revision/results/headline_canonical.json`` (long-form schema:
``schema``, ``data_hash``, ``metric_helpers``, ``models``, ``rows`` + a
``device``/``dtype`` manifest and a ``source``/``generation_seed`` marker).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────────
# Repo-root resolution (copied verbatim from run_multiseed_rollup.py:42-59 /
# run_recover_canonical.py:63-77 — the driver may run from a worktree).
# ─────────────────────────────────────────────────────────────────────────────
def _find_repo_root() -> Path:
    p = Path(__file__).resolve().parent
    for cand in [p, *p.parents]:
        if (cand / "revision" / "core" / "preprocessing.py").exists():
            return cand
    p = Path.cwd().resolve()
    for cand in [p, *p.parents]:
        if (cand / "revision" / "core" / "preprocessing.py").exists():
            return cand
    raise RuntimeError("repo root not found (revision/core/preprocessing.py)")


REPO = _find_repo_root()
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

RESULTS = REPO / "revision" / "results"

# eval.py helper contract string — IDENTICAL token to baseline_comparison.json
# so the headline reconciles with the matched-budget table (D-10-20).
METRIC_HELPERS = "revision.core.eval ONLY (D-10-20)"

NLAGS = 9  # ACF lag count — IDENTICAL to run_dualscale_fidelity:106
# (window length is 10 -> max 9 lags + lag 0 = 10 entries; this exact value
# is load-bearing so the headline ACF rows reconcile with
# fidelity_dualscale.json, D-11-10).
DTW_N_PAIRS = 100  # DTW sub-sample — identical recipe (T-11-03).

_LOG_RETURN_NA = (
    "Pipeline B headline emits log_return-scale metrics; this marker is "
    "unused for B but kept for schema rectangularity (D-11-09)."
)


def _resolve_checkpoint() -> Path:
    """Locate ``best_checkpoint.pt`` (D-14-02 ground truth).

    .gitignored, so in a Claude Code worktree it is NOT copied in — it lives
    in the main checkout. Resolve via, in order: REPO root, cwd, then the
    main-repo toplevel that this worktree's ``.git`` file points at. Copied
    verbatim from run_recover_canonical.py:101-133 (T-14-14 — same ground
    truth tensor as Plan 01).
    """
    candidates = [REPO / "best_checkpoint.pt", Path.cwd() / "best_checkpoint.pt"]

    git_link = REPO / ".git"
    if git_link.is_file():
        try:
            gitdir = git_link.read_text().strip()
            if gitdir.startswith("gitdir:"):
                wt_git = Path(gitdir.split(":", 1)[1].strip())
                for anc in wt_git.parents:
                    if anc.name == ".git":
                        main_root = anc.parent
                        candidates.append(main_root / "best_checkpoint.pt")
                        break
        except OSError:
            pass

    for c in candidates:
        if c.exists():
            return c.resolve()
    raise RuntimeError(
        "best_checkpoint.pt not found (D-14-02 ground truth missing); "
        f"looked in: {[str(c) for c in candidates]}"
    )


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _scalar(v) -> float:
    """Read a stored 0-dim tensor / python scalar VERBATIM (D-14-05)."""
    try:
        return float(v.item())
    except AttributeError:
        return float(v)


def _compute_data_hash(csv_path: Path) -> str:
    """sha256(real_OD bytes)[:16] recomputed from load_and_preprocess.

    Identical recipe to run_baselines._compute_data_hash / the matched-2000ep
    sweep — pins the headline to the exact OD tensor so the strict accept gate
    can prove the headline and every comparison row consumed the same data.
    """
    from revision.core.data import load_and_preprocess

    od = load_and_preprocess(str(csv_path))["OD"].cpu().numpy()
    return hashlib.sha256(od.tobytes()).hexdigest()[:16]


def _build_real_references(csv_path: Path) -> dict:
    """Build the real OD + log-return reference arrays.

    Reuses the EXACT construction run_dualscale_fidelity.build_real_references
    uses (``real_windowed_OD`` rolling_window step 2 + ``real_log_delta`` =
    ``d_real["log_delta"]``) so the headline numbers reconcile with
    ``fidelity_dualscale.json`` / ``baseline_comparison.json`` (D-11-10).
    """
    import numpy as np  # noqa: F401  (kept for parity w/ peer driver imports)

    from revision.core import WINDOW_LENGTH
    from revision.core.data import load_and_preprocess, rolling_window

    d_real = load_and_preprocess(str(csv_path))
    real_windowed_OD = rolling_window(
        d_real["OD"], WINDOW_LENGTH, 2
    ).cpu().numpy()
    real_log_delta = d_real["log_delta"].cpu().numpy()
    return {
        "real_windowed_OD": real_windowed_OD,
        "real_OD_flat": real_windowed_OD.reshape(-1),
        "real_log_delta": real_log_delta,
    }


def _generate_headline_samples(gen, n: int, seed: int):
    """Generate ``n`` headline windows in [-1, 1] space from the frozen circuit.

    Copied VERBATIM from run_baselines.generate_wgan_samples (the canonical
    *0.1 sample space the shared reconstruct_od inverse consumes; RESEARCH
    Pitfall 6 — Apple MPS has no float64 statevector path so the quantum
    generator stays on CPU). FIXED ``np.random.default_rng(seed)`` — no global
    ``np.random.seed``. The seed is the recorded ``generation_seed`` (D-14-05).
    """
    import numpy as np
    import torch

    from revision.core import BATCH_SIZE, NOISE_HIGH, NOISE_LOW, NUM_QUBITS

    gen = gen.to("cpu")
    rng = np.random.default_rng(seed)
    out_parts: list = []
    remaining = n
    with torch.no_grad():
        while remaining > 0:
            bs = min(BATCH_SIZE, remaining)
            noise = torch.tensor(
                rng.uniform(NOISE_LOW, NOISE_HIGH, size=(NUM_QUBITS, bs)),
                dtype=torch.float32,
            )
            out = gen(noise).to(torch.float64) * 0.1
            out_parts.append(out.cpu().numpy())
            remaining -= bs
    return np.concatenate(out_parts, axis=0)[:n]


def _reconstruct_od_from_samples(samples_pm1, mu: float, sigma: float,
                                 r_min: float, r_max: float,
                                 od_starts_pool, seed: int):
    """Pipeline-B [-1,1] -> OD reconstruction, VERBATIM from
    run_dualscale_fidelity.reconstruct_od (Pipeline-B branch).

    The ``np.random.default_rng(seed*7919+1)`` od_start draw is load-bearing —
    do NOT change it (matches the frozen baseline reconstruction recipe so the
    headline reconciles with fidelity_dualscale.json). mu/sigma are the
    checkpoint's STORED scalars (D-14-05).
    """
    import numpy as np
    import torch

    from revision.core.preprocessing import inverse_logreturns

    samples_pm1 = np.asarray(samples_pm1, dtype=np.float64)
    r_norm = ((samples_pm1 + 1.0) / 2.0) * (r_max - r_min) + r_min
    rng = np.random.default_rng(seed * 7919 + 1)
    od_start_per_window = rng.choice(
        od_starts_pool, size=r_norm.shape[0], replace=True
    )
    r_norm_t = torch.tensor(r_norm)
    od_start_t = torch.tensor(od_start_per_window)
    od_full = inverse_logreturns(
        r_norm_t, od_start_t, torch.tensor(mu), torch.tensor(sigma)
    )
    od = od_full.cpu().numpy()
    if od.shape[1] == 11:
        od = od[:, :10]
    return od, r_norm


def _od_scale_rows(od, real_OD_flat, real_windowed_OD) -> list:
    """Every eval.py metric on the OD scale (D-11-10 — NO new metric math).

    Structure copied from run_dualscale_fidelity._od_scale_rows (same metric
    suite + DTW sub-sample recipe). Every row carries ``scale="OD"``.
    """
    import numpy as np

    from revision.core.eval import (
        compute_acf,
        compute_dtw,
        compute_emd,
        compute_moments,
    )

    mk, p = "quantum", "B"
    out = []
    synth_flat = od.reshape(-1)
    out.append(dict(model_kind=mk, pipeline=p, metric_name="emd",
                    scale="OD", value=compute_emd(real_OD_flat, synth_flat)))
    for k, v in compute_moments(synth_flat).items():
        out.append(dict(model_kind=mk, pipeline=p,
                        metric_name=f"moment_{k}", scale="OD", value=v))
    acfs = np.stack([compute_acf(w, nlags=NLAGS) for w in od])
    for lag in range(NLAGS + 1):
        out.append(dict(model_kind=mk, pipeline=p,
                        metric_name=f"acf_lag{lag}_mean", scale="OD",
                        value=float(acfs[:, lag].mean())))
        out.append(dict(model_kind=mk, pipeline=p,
                        metric_name=f"acf_lag{lag}_std", scale="OD",
                        value=float(acfs[:, lag].std())))
    rng = np.random.default_rng(42 * 31)
    synth_idx = rng.choice(od.shape[0],
                           size=min(DTW_N_PAIRS, od.shape[0]), replace=False)
    real_idx = rng.choice(real_windowed_OD.shape[0],
                          size=min(64, real_windowed_OD.shape[0]),
                          replace=False)
    dtw_vals = []
    for i in synth_idx:
        best = min(compute_dtw(od[i], real_windowed_OD[j]) for j in real_idx)
        dtw_vals.append(best)
    out.append(dict(model_kind=mk, pipeline=p, metric_name="dtw_mean",
                    scale="OD", value=float(np.mean(dtw_vals))))
    out.append(dict(model_kind=mk, pipeline=p, metric_name="dtw_median",
                    scale="OD", value=float(np.median(dtw_vals))))
    out.append(dict(model_kind=mk, pipeline=p, metric_name="dtw_std",
                    scale="OD", value=float(np.std(dtw_vals))))
    return out


def _log_return_rows(r_norm, real_log_delta) -> list:
    """The SAME metric set on the log-return scale (Pipeline B real values).

    Structure copied from run_dualscale_fidelity._log_return_rows (Pipeline-B
    branch). real reference is ``real_log_delta`` so numbers reconcile with
    ``baseline_comparison.json``'s ``scale="transformed"`` rows.
    """
    import numpy as np

    from revision.core.eval import (
        compute_acf,
        compute_dtw,
        compute_emd,
        compute_moments,
    )

    mk, p = "quantum", "B"
    out = []
    trans_flat = np.asarray(r_norm, dtype=np.float64).reshape(-1)
    out.append(dict(model_kind=mk, pipeline=p, metric_name="emd",
                    scale="log_return",
                    value=compute_emd(real_log_delta, trans_flat)))
    for k, v in compute_moments(trans_flat).items():
        out.append(dict(model_kind=mk, pipeline=p,
                        metric_name=f"moment_{k}", scale="log_return",
                        value=v))
    win = np.asarray(r_norm, dtype=np.float64)
    acfs = np.stack([compute_acf(w, nlags=NLAGS) for w in win])
    for lag in range(NLAGS + 1):
        out.append(dict(model_kind=mk, pipeline=p,
                        metric_name=f"acf_lag{lag}_mean", scale="log_return",
                        value=float(acfs[:, lag].mean())))
        out.append(dict(model_kind=mk, pipeline=p,
                        metric_name=f"acf_lag{lag}_std", scale="log_return",
                        value=float(acfs[:, lag].std())))
    rng = np.random.default_rng(42 * 31)
    real_w = real_log_delta.reshape(-1)
    n_real_w = max(1, real_w.shape[0] // win.shape[1])
    real_windows = real_w[: n_real_w * win.shape[1]].reshape(
        n_real_w, win.shape[1]
    )
    synth_idx = rng.choice(win.shape[0],
                           size=min(DTW_N_PAIRS, win.shape[0]), replace=False)
    real_idx = rng.choice(real_windows.shape[0],
                          size=min(64, real_windows.shape[0]), replace=False)
    dtw_vals = []
    for i in synth_idx:
        best = min(compute_dtw(win[i], real_windows[j]) for j in real_idx)
        dtw_vals.append(best)
    out.append(dict(model_kind=mk, pipeline=p, metric_name="dtw_mean",
                    scale="log_return", value=float(np.mean(dtw_vals))))
    out.append(dict(model_kind=mk, pipeline=p, metric_name="dtw_median",
                    scale="log_return", value=float(np.median(dtw_vals))))
    out.append(dict(model_kind=mk, pipeline=p, metric_name="dtw_std",
                    scale="log_return", value=float(np.std(dtw_vals))))
    return out


def generate_headline(csv_path: Path, generation_seed: int,
                       out_path: Path) -> dict:
    """Generate the canonical headline JSON from the FROZEN checkpoint."""
    import numpy as np
    import torch

    from revision.core import WINDOW_LENGTH
    from revision.core.data import load_and_preprocess, rolling_window
    from revision.core.models.quantum import QuantumGenerator
    from revision.core.preprocessing import forward_logreturns

    # ── Load the locked canonical config (Plan 01, T-14-14 ground truth) ──────
    lock_path = RESULTS / "canonical_config_lock.json"
    if not lock_path.exists():
        raise AssertionError(
            "canonical_config_lock.json missing — Plan 01 "
            "(--assert-equivalence) must precede the headline (D-14-07)"
        )
    lock = json.loads(lock_path.read_text())

    # ── T-14-14 checkpoint identity gate (explicit raise — python -O safe) ────
    ckpt_path = _resolve_checkpoint()
    actual_sha = _sha256(ckpt_path)
    locked_sha = lock["checkpoint_sha256"]
    if actual_sha != locked_sha:
        raise AssertionError(
            f"best_checkpoint.pt sha256 {actual_sha} != locked "
            f"{locked_sha} (canonical_config_lock.json) — checkpoint "
            "identity reuse / tampering (T-14-14 BLOCK)"
        )

    ck = torch.load(ckpt_path, map_location="cpu", weights_only=False)

    # ── Ground-truth shape gate (explicit raise) ──────────────────────────────
    pqc = ck["params_pqc"]
    if tuple(pqc.shape) != (55,):
        raise AssertionError(
            f"checkpoint params_pqc shape {tuple(pqc.shape)} != (55,) — "
            "not the canonical 55-param IQP:SEL ground truth (D-14-02)"
        )
    ckpt_epoch = int(ck["epoch"])
    if ckpt_epoch != lock["checkpoint_epoch"]:
        raise AssertionError(
            f"checkpoint epoch {ckpt_epoch} != locked "
            f"{lock['checkpoint_epoch']} (D-14-03 headline-source mismatch)"
        )

    # ── STORED mu/sigma read VERBATIM — NEVER recompute (D-14-05) ─────────────
    stored_mu = _scalar(ck["mu"])
    stored_sigma = _scalar(ck["sigma"])
    # Cross-check the stored scalars match Plan 01's locked record (the lock
    # JSON copied them verbatim from this same checkpoint). Explicit-raise.
    if abs(stored_mu - float(lock["mu"])) > 1e-12 or \
       abs(stored_sigma - float(lock["sigma"])) > 1e-12:
        raise AssertionError(
            f"checkpoint mu/sigma ({stored_mu},{stored_sigma}) != locked "
            f"({lock['mu']},{lock['sigma']}) — D-14-05 stored-stat mismatch"
        )

    # ── Construct the locked NON-default 55-param iqp_sel_55 circuit ──────────
    decomp = lock["decomposition"]
    q = int(decomp["num_qubits"])
    gen = QuantumGenerator(
        num_qubits=q,
        num_layers=int(decomp["num_layers"]),
        window_length=2 * q,
        circuit_id=lock["locked_circuit_id"],
    )
    if gen.num_params != 55:
        raise AssertionError(
            f"locked circuit num_params {gen.num_params} != 55 "
            f"(circuit_id={lock['locked_circuit_id']}) — D-14-07 BLOCK"
        )

    # ── Load epoch-1969 params_pqc into the circuit (CPU; D-14-11) ────────────
    with torch.no_grad():
        if gen.params_pqc.shape != pqc.shape:
            raise AssertionError(
                f"param tensor shape mismatch: circuit "
                f"{tuple(gen.params_pqc.shape)} vs checkpoint "
                f"{tuple(pqc.shape)} — D-14-07 BLOCK"
            )
        gen.params_pqc.copy_(pqc.to(gen.params_pqc.dtype))

    # Structural forward-pass gate — the frozen circuit must consume 55.
    consumed = gen.last_param_index(torch.zeros(q))
    if consumed != 55:
        raise AssertionError(
            f"structural forward-pass consumed {consumed} != 55 — frozen "
            "circuit NOT config-equivalent to the checkpoint (D-14-07 BLOCK)"
        )

    # ── T-14-04 device/dtype manifest — hard-assert the actual backend ────────
    # PennyLane default.qubit is CPU-only (D-14-11). The headline generation
    # runs the trained generator on CPU in float64 (RESEARCH Pitfall 6). Fail
    # loudly if the params somehow landed off-CPU or off-float32.
    gen = gen.to("cpu")
    actual_device = str(gen.params_pqc.device)
    actual_dtype = str(gen.params_pqc.dtype)
    pl_device = gen.dev.name if hasattr(gen.dev, "name") else str(gen.dev)
    if not actual_device.startswith("cpu"):
        raise AssertionError(
            f"device manifest violation: params on {actual_device}, "
            "expected cpu (PennyLane default.qubit is CPU-only, D-14-11) "
            "— silent device fallback (T-14-04 BLOCK)"
        )
    if actual_dtype != "torch.float32":
        raise AssertionError(
            f"dtype manifest violation: params {actual_dtype}, expected "
            "torch.float32 (params_pqc is a float32 nn.Parameter) "
            "— silent dtype fallback (T-14-04 BLOCK)"
        )
    if "default.qubit" not in pl_device:
        raise AssertionError(
            f"backend manifest violation: PennyLane device {pl_device!r} "
            "is not default.qubit (D-14-11 backend lock; lightning.qubit "
            "forbidden) — T-14-04 BLOCK"
        )
    device_manifest = {
        "torch_device": actual_device,
        "torch_dtype": actual_dtype,
        "pennylane_device": pl_device,
        "diff_method": gen.diff_method,
        "backend_assertion": "PASSED (CPU + default.qubit + float32 params)",
        "note": (
            "PennyLane default.qubit statevector path is CPU-only (D-14-11); "
            "the quantum headline row is CORRECTLY CPU — this is not a "
            "silent classical fallback (T-14-04)."
        ),
    }

    # ── Build native Pipeline-B reconstruction inputs (D-14-06) ───────────────
    raw = load_and_preprocess(str(csv_path))
    od = raw["OD"]
    r_norm, _mu_fresh, _sigma_fresh = forward_logreturns(od)
    # NOTE: _mu_fresh/_sigma_fresh are the freshly-computed pipeline stats and
    # are DELIBERATELY UNUSED for reconstruction (D-14-05 — the headline uses
    # the checkpoint's STORED mu/sigma). They only define the [-1,1] min-max
    # window mapping (r_min/r_max), which is a pipeline-shape constant, not a
    # standardization stat.
    r_min = float(torch.min(r_norm).item())
    r_max = float(torch.max(r_norm).item())
    n_lr = r_norm.shape[0]
    start_indices = list(range(0, n_lr - WINDOW_LENGTH + 1, 2))
    od_starts_pool = torch.stack([od[i] for i in start_indices]).cpu().numpy()
    n_real_windows = int(
        rolling_window(
            2.0 * (r_norm - torch.min(r_norm))
            / (torch.max(r_norm) - torch.min(r_norm)) - 1.0,
            WINDOW_LENGTH, 2,
        ).shape[0]
    )

    # ── Generate samples — FIXED seed, STORED mu/sigma (D-14-05) ──────────────
    n_synth = 10 * n_real_windows
    samples_pm1 = _generate_headline_samples(gen, n_synth, generation_seed)
    od_synth, r_norm_synth = _reconstruct_od_from_samples(
        samples_pm1, stored_mu, stored_sigma, r_min, r_max,
        od_starts_pool, generation_seed,
    )

    # ── Evaluate via revision.core.eval ONLY (D-10-20), dual-scale ────────────
    refs = _build_real_references(csv_path)
    rows = []
    rows += _od_scale_rows(
        od_synth, refs["real_OD_flat"], refs["real_windowed_OD"]
    )
    rows += _log_return_rows(r_norm_synth, refs["real_log_delta"])

    data_hash = _compute_data_hash(csv_path)

    doc = {
        "schema": "long-form headline rows[] + models[] (Phase 14 D-14-03/05)",
        "source": "frozen_checkpoint_epoch_1969",
        "source_note": (
            "Headline generated by loading best_checkpoint.pt's epoch-1969 "
            "params_pqc (55,) into the locked iqp_sel_55 circuit and "
            "generating with the checkpoint's STORED mu/sigma + a FIXED "
            "generation seed. This is NOT a retrain — the matched-2000ep "
            "55-param run is a separate NON-load-bearing reproduction "
            "instance tagged source='matched2000_reproduction' (D-14-10)."
        ),
        "generation_seed": int(generation_seed),
        "checkpoint_epoch": ckpt_epoch,
        "checkpoint_emd": float(ck["emd"]),
        "checkpoint_sha256": actual_sha,
        "checkpoint_filename": ckpt_path.name,
        "locked_circuit_id": lock["locked_circuit_id"],
        "param_count": 55,
        "structural_forward_pass_consumed": consumed,
        "native_pipeline": lock["native_pipeline"],
        "mu": stored_mu,
        "sigma": stored_sigma,
        "mu_sigma_provenance": (
            "checkpoint STORED scalars, read verbatim — NEVER recomputed "
            "(D-14-05; freshly-computed stats would not reproduce the 16 "
            "canonical figures)"
        ),
        "data_hash": data_hash,
        "metric_helpers": METRIC_HELPERS,
        "device": device_manifest,
        "dtype": actual_dtype,
        "model_kinds": ["quantum"],
        "pipelines": ["B"],
        "scales": ["OD", "log_return"],
        "models": [
            {
                "kind": "quantum",
                "parameter_count": 55,
                "family": "adversarial-quantum",
                "circuit_id": lock["locked_circuit_id"],
                "train_protocol_notes": (
                    "Canonical 55-param IQP:SEL recovered from "
                    "best_checkpoint.pt (epoch 1969); headline is the FROZEN "
                    "checkpoint, NOT a retrain (D-14-03). Native Pipeline B "
                    "(log-return standardization, D-14-06); generation uses "
                    "the checkpoint's STORED mu/sigma + a fixed seed "
                    "(D-14-05)."
                ),
            }
        ],
        "rows": rows,
    }

    RESULTS.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(doc, indent=2, sort_keys=False) + "\n")
    print(
        f"[canonical-headline] wrote {out_path} "
        f"({len(rows)} rows, source={doc['source']}, "
        f"generation_seed={generation_seed}, "
        f"device={device_manifest['torch_device']}, "
        f"data_hash={data_hash})"
    )
    return doc


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Phase 14 Tier-2 — generate the canonical headline result "
        "from the FROZEN best_checkpoint.pt (epoch 1969); NOT a retrain "
        "(D-14-03/05)."
    )
    ap.add_argument(
        "--csv-path",
        type=Path,
        default=Path("./data.csv"),
        help="OD CSV (same data the 09.1 quantum runs used).",
    )
    ap.add_argument(
        "--generation-seed",
        type=int,
        default=42,
        help="FIXED generation seed recorded in the output (D-14-05).",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=RESULTS / "headline_canonical.json",
        help="Output JSON path.",
    )
    args = ap.parse_args()
    generate_headline(args.csv_path, args.generation_seed, args.out)


if __name__ == "__main__":
    main()
